-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 23-Nov-14 16:09:04
-- Path: /home/jtijhuis/epo3a5/chip/subsystems/SPI/GWTF/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Spi IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32: STD_LOGIC;
  SIGNAL N_33, N_34, N_35, N_36, N_37, N_38, N_39, N_40: STD_LOGIC;
  SIGNAL N_41, N_42, N_43, N_44, N_45, N_46, N_47, N_48: STD_LOGIC;
  SIGNAL N_49, N_50, N_51, N_52, N_53, N_54, N_55: STD_LOGIC;
  SIGNAL count_1_port: STD_LOGIC;
  SIGNAL count_0_port: STD_LOGIC;
  SIGNAL shift: STD_LOGIC;
  SIGNAL count_reset: STD_LOGIC;
  SIGNAL count_3_port: STD_LOGIC;
  SIGNAL count_2_port: STD_LOGIC;

  SIGNAL read_out_int: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL sclk_int: STD_LOGIC;
  SIGNAL mosi_int: STD_LOGIC;

BEGIN

  read_out <= read_out_int;
  sclk <= sclk_int;
  mosi <= mosi_int;

  read_out_int(7) <= mosi_int;

  cnt1_U13: ex210 PORT MAP (N_45, N_44, N_51);
  cnt1_U16: ex210 PORT MAP (count_1_port, count_0_port, N_38);
  cnt1_U11: ex210 PORT MAP (count_3_port, N_50, N_49);
  ctrl1_U35: iv110 PORT MAP (count_0_port, N_35);
  ctrl1_U22: iv110 PORT MAP (N_36, N_47);
  ctrl1_U27: iv110 PORT MAP (shift, count_reset);
  ctrl1_U32: iv110 PORT MAP (N_52, N_53);
  cnt1_U10: iv110 PORT MAP (count_0_port, N_37);
  cnt1_U15: iv110 PORT MAP (count_2_port, N_45);
  ctrl1_U26: mu111 PORT MAP (reset, send, N_54, N_48);
  shft1_U63: na210 PORT MAP (read_out_int(6), N_27, N_4);
  shft1_U61: na210 PORT MAP (write_in(6), write_enable, N_3);
  shft1_U62: na210 PORT MAP (read_out_int(5), N_31, N_1);
  shft1_U65: na210 PORT MAP (write_in(7), write_enable, N_6);
  shft1_U68: na210 PORT MAP (mosi_int, N_27, N_5);
  shft1_U66: na210 PORT MAP (read_out_int(6), N_31, N_2);
  shft1_U43: na210 PORT MAP (read_out_int(1), N_27, N_12);
  shft1_U41: na210 PORT MAP (write_in(1), write_enable, N_9);
  shft1_U57: na210 PORT MAP (write_in(5), write_enable, N_10);
  shft1_U59: na210 PORT MAP (read_out_int(5), N_27, N_8);
  shft1_U51: na210 PORT MAP (read_out_int(3), N_27, N_14);
  shft1_U49: na210 PORT MAP (write_in(3), write_enable, N_15);
  shft1_U55: na210 PORT MAP (read_out_int(4), N_27, N_17);
  shft1_U46: na210 PORT MAP (read_out_int(1), N_31, N_22);
  shft1_U58: na210 PORT MAP (read_out_int(4), N_31, N_19);
  shft1_U50: na210 PORT MAP (read_out_int(2), N_31, N_21);
  shft1_U54: na210 PORT MAP (read_out_int(3), N_31, N_20);
  shft1_U39: na210 PORT MAP (read_out_int(0), N_27, N_30);
  shft1_U42: na210 PORT MAP (read_out_int(0), N_31, N_24);
  shft1_U53: na210 PORT MAP (write_in(4), write_enable, N_23);
  shft1_U47: na210 PORT MAP (read_out_int(2), N_27, N_25);
  shft1_U45: na210 PORT MAP (write_in(2), write_enable, N_26);
  shft1_U37: na210 PORT MAP (write_in(0), write_enable, N_33);
  shft1_U38: na210 PORT MAP (miso, N_31, N_32);
  ctrl1_U30: na210 PORT MAP (N_41, shift, N_42);
  ctrl1_U28: na210 PORT MAP (N_42, N_55, N_43);
  cnt1_U14: na210 PORT MAP (count_1_port, count_0_port, N_44);
  shft1_U60: na310 PORT MAP (N_4, N_1, N_3, N_29);
  shft1_U64: na310 PORT MAP (N_5, N_2, N_6, N_7);
  shft1_U40: na310 PORT MAP (N_12, N_24, N_9, N_13);
  shft1_U56: na310 PORT MAP (N_8, N_19, N_10, N_11);
  shft1_U48: na310 PORT MAP (N_14, N_21, N_15, N_16);
  shft1_U52: na310 PORT MAP (N_17, N_20, N_23, N_18);
  shft1_U44: na310 PORT MAP (N_25, N_22, N_26, N_28);
  shft1_U36: na310 PORT MAP (N_30, N_32, N_33, N_34);
  ctrl1_U33: na310 PORT MAP (count_3_port, N_35, N_40, N_41);
  ctrl1_U29: na310 PORT MAP (send, N_53, N_54, N_55);
  shft1_reg_shift_reg_5_inst: dfa11 PORT MAP (N_11, reset, clk, read_out_int(5));
  shft1_reg_shift_reg_7_inst: dfa11 PORT MAP (N_7, reset, clk, mosi_int);
  shft1_reg_shift_reg_1_inst: dfa11 PORT MAP (N_13, reset, clk, read_out_int(1));
  shft1_reg_shift_reg_4_inst: dfa11 PORT MAP (N_18, reset, clk, read_out_int(4));
  shft1_reg_shift_reg_3_inst: dfa11 PORT MAP (N_16, reset, clk, read_out_int(3));
  shft1_reg_shift_reg_0_inst: dfa11 PORT MAP (N_34, reset, clk, read_out_int(0));
  shft1_reg_shift_reg_6_inst: dfa11 PORT MAP (N_29, reset, clk, read_out_int(6));
  shft1_reg_shift_reg_2_inst: dfa11 PORT MAP (N_28, reset, clk, read_out_int(2));
  ctrl1_state_reg_1_inst: dfa11 PORT MAP (N_43, reset, clk, N_52);
  ctrl1_state_reg_0_inst: dfa11 PORT MAP (N_47, reset, clk, N_54);
  cnt1_count_reg_0_inst: dfa11 PORT MAP (N_37, count_reset, sclk_int, count_0_port);
  cnt1_count_reg_1_inst: dfa11 PORT MAP (N_38, count_reset, sclk_int, count_1_port);
  cnt1_count_reg_3_inst: dfa11 PORT MAP (N_49, count_reset, sclk_int, count_3_port);
  cnt1_count_reg_2_inst: dfa11 PORT MAP (N_51, count_reset, sclk_int, count_2_port);
  shft1_U69: no210 PORT MAP (shift, write_enable, N_27);
  shft1_U67: no210 PORT MAP (N_27, write_enable, N_31);
  ctrl1_U34: no210 PORT MAP (count_2_port, count_1_port, N_40);
  ctrl1_U24: no210 PORT MAP (count_reset, N_41, N_39);
  ctrl1_U23: no210 PORT MAP (N_46, N_39, N_36);
  ctrl1_U21: no210 PORT MAP (clk, count_reset, sclk_int);
  ctrl1_U25: no210 PORT MAP (N_52, N_48, N_46);
  ctrl1_U31: no210 PORT MAP (N_53, N_54, shift);
  cnt1_U12: no210 PORT MAP (N_44, N_45, N_50);

END extracted;



