Blackbox

* Generated by: xspice 2.48 07-May-2008
* Date: 12-Dec-14 20:50:23
* Path: /home/wbouwmeester/Documents/BetterBlackBox/GWTF/test
* Language: SPICE

* circuit Blackbox 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
*
*   1 pbulk        2 nbulk        3 sclk_s_0     4 sclk_s_1     5 s
*   6 vdd          7 ss_m_0       8 ss_s_0       9 ss_s_1      10 miso_m_0
*  11 miso_m_1    12 sclk_m_0    13 sclk_m_1    14 mosi_m_0    15 mosi_m_1
*  16 mosi_s_0    17 mosi_s_1    18 ss_m_1      19 miso_s_0    20 miso_s_1
*
m1 21 5 0 2 nenh w=23.2u l=1.6u
m2 21 5 6 1 penh w=29.6u l=1.6u
m3 22 5 6 1 penh w=29.6u l=1.6u
m4 22 5 0 2 nenh w=23.2u l=1.6u
m5 23 5 0 2 nenh w=23.2u l=1.6u
m6 24 21 6 1 penh w=29.6u l=1.6u
m7 25 22 6 1 penh w=29.6u l=1.6u
m8 26 5 0 2 nenh w=23.2u l=1.6u
m9 23 7 27 2 nenh w=23.2u l=1.6u
m10 24 7 27 1 penh w=29.6u l=1.6u
m11 25 18 28 1 penh w=29.6u l=1.6u
m12 26 18 28 2 nenh w=23.2u l=1.6u
m13 29 21 27 2 nenh w=23.2u l=1.6u
m14 30 5 27 1 penh w=29.6u l=1.6u
m15 31 5 28 1 penh w=29.6u l=1.6u
m16 32 22 28 2 nenh w=23.2u l=1.6u
m17 29 18 0 2 nenh w=23.2u l=1.6u
m18 30 18 6 1 penh w=29.6u l=1.6u
m19 31 7 6 1 penh w=29.6u l=1.6u
m20 32 7 0 2 nenh w=23.2u l=1.6u
m21 9 27 0 2 nenh w=23.2u l=1.6u
m22 9 27 6 1 penh w=29.6u l=1.6u
m23 8 28 6 1 penh w=29.6u l=1.6u
m24 8 28 0 2 nenh w=23.2u l=1.6u
m25 33 5 0 2 nenh w=23.2u l=1.6u
m26 33 5 6 1 penh w=29.6u l=1.6u
m27 34 5 6 1 penh w=29.6u l=1.6u
m28 34 5 0 2 nenh w=23.2u l=1.6u
m29 35 5 0 2 nenh w=23.2u l=1.6u
m30 36 33 6 1 penh w=29.6u l=1.6u
m31 37 34 6 1 penh w=29.6u l=1.6u
m32 38 5 0 2 nenh w=23.2u l=1.6u
m33 35 14 39 2 nenh w=23.2u l=1.6u
m34 36 14 39 1 penh w=29.6u l=1.6u
m35 37 15 40 1 penh w=29.6u l=1.6u
m36 38 15 40 2 nenh w=23.2u l=1.6u
m37 41 33 39 2 nenh w=23.2u l=1.6u
m38 42 5 39 1 penh w=29.6u l=1.6u
m39 43 5 40 1 penh w=29.6u l=1.6u
m40 44 34 40 2 nenh w=23.2u l=1.6u
m41 41 15 0 2 nenh w=23.2u l=1.6u
m42 42 15 6 1 penh w=29.6u l=1.6u
m43 43 14 6 1 penh w=29.6u l=1.6u
m44 44 14 0 2 nenh w=23.2u l=1.6u
m45 17 39 0 2 nenh w=23.2u l=1.6u
m46 17 39 6 1 penh w=29.6u l=1.6u
m47 16 40 6 1 penh w=29.6u l=1.6u
m48 16 40 0 2 nenh w=23.2u l=1.6u
m49 45 5 0 2 nenh w=23.2u l=1.6u
m50 45 5 6 1 penh w=29.6u l=1.6u
m51 46 5 6 1 penh w=29.6u l=1.6u
m52 46 5 0 2 nenh w=23.2u l=1.6u
m53 47 5 0 2 nenh w=23.2u l=1.6u
m54 48 45 6 1 penh w=29.6u l=1.6u
m55 49 46 6 1 penh w=29.6u l=1.6u
m56 50 5 0 2 nenh w=23.2u l=1.6u
m57 47 12 51 2 nenh w=23.2u l=1.6u
m58 48 12 51 1 penh w=29.6u l=1.6u
m59 49 13 52 1 penh w=29.6u l=1.6u
m60 50 13 52 2 nenh w=23.2u l=1.6u
m61 53 45 51 2 nenh w=23.2u l=1.6u
m62 54 5 51 1 penh w=29.6u l=1.6u
m63 55 5 52 1 penh w=29.6u l=1.6u
m64 56 46 52 2 nenh w=23.2u l=1.6u
m65 53 13 0 2 nenh w=23.2u l=1.6u
m66 54 13 6 1 penh w=29.6u l=1.6u
m67 55 12 6 1 penh w=29.6u l=1.6u
m68 56 12 0 2 nenh w=23.2u l=1.6u
m69 4 51 0 2 nenh w=23.2u l=1.6u
m70 4 51 6 1 penh w=29.6u l=1.6u
m71 3 52 6 1 penh w=29.6u l=1.6u
m72 3 52 0 2 nenh w=23.2u l=1.6u
m73 57 5 0 2 nenh w=23.2u l=1.6u
m74 57 5 6 1 penh w=29.6u l=1.6u
m75 58 5 6 1 penh w=29.6u l=1.6u
m76 58 5 0 2 nenh w=23.2u l=1.6u
m77 59 5 0 2 nenh w=23.2u l=1.6u
m78 60 57 6 1 penh w=29.6u l=1.6u
m79 61 58 6 1 penh w=29.6u l=1.6u
m80 62 5 0 2 nenh w=23.2u l=1.6u
m81 59 19 63 2 nenh w=23.2u l=1.6u
m82 60 19 63 1 penh w=29.6u l=1.6u
m83 61 20 64 1 penh w=29.6u l=1.6u
m84 62 20 64 2 nenh w=23.2u l=1.6u
m85 65 57 63 2 nenh w=23.2u l=1.6u
m86 66 5 63 1 penh w=29.6u l=1.6u
m87 67 5 64 1 penh w=29.6u l=1.6u
m88 68 58 64 2 nenh w=23.2u l=1.6u
m89 65 20 0 2 nenh w=23.2u l=1.6u
m90 66 20 6 1 penh w=29.6u l=1.6u
m91 67 19 6 1 penh w=29.6u l=1.6u
m92 68 19 0 2 nenh w=23.2u l=1.6u
m93 11 63 0 2 nenh w=23.2u l=1.6u
m94 11 63 6 1 penh w=29.6u l=1.6u
m95 10 64 6 1 penh w=29.6u l=1.6u
m96 10 64 0 2 nenh w=23.2u l=1.6u
*
* namelist Blackbox
*
*   0 vss          1 pbulk        2 nbulk        3 sclk_s_0     4 sclk_s_1
*   5 s            6 vdd          7 ss_m_0       8 ss_s_0       9 ss_s_1
*  10 miso_m_0    11 miso_m_1    12 sclk_m_0    13 sclk_m_1    14 mosi_m_0
*  15 mosi_m_1    16 mosi_s_0    17 mosi_s_1    18 ss_m_1      19 miso_s_0
*  20 miso_s_1    21 5           22 6           23 1           24 2
*  25 3           26 4           27 11          28 12          29 7
*  30 8           31 9           32 10          33 17          34 18
*  35 13          36 14          37 15          38 16          39 23
*  40 24          41 19          42 20          43 21          44 22
*  45 29          46 30          47 25          48 26          49 27
*  50 28          51 35          52 36          53 31          54 32
*  55 33          56 34          57 41          58 42          59 37
*  60 38          61 39          62 40          63 47          64 48
*  65 43          66 44          67 45          68 46
*
* end Blackbox

* range: w >= 3u,  3u >= l >= 1.6u
*        |Vd| <= 5.5v,  |Vg| > 1.5v, |Vb| < 5v

* originally we had rsh=55 (nenh) and rsh=75 (penh) but its influence
* can be neglected and it spoils the simulations if we use "ghoti -r"

.model nenh nmos        level=2
+                       ld=0.325u       tox=250e-10     nsub=2e16
+                       vto=0.7         uo=510          uexp=0.22
+                       ucrit=24.3k     delta=0.4       xj=0.4u
+                       vmax=54k        neff=4.0        rsh=0
+                       nfs=0e11        js=2u           cj=130u
+                       cjsw=620p       mj=0.53         mjsw=0.53
+                       pb=0.68v        cgdo=320p       cgso=320p
* end nenh

.model penh pmos        level=2
+                       ld=0.3u         tox=250e-10     nsub=5e16
+                       vto=-1.1        uo=210          uexp=0.33
+                       ucrit=51k       delta=0.4       xj=0.5u
+                       vmax=47k        neff=0.88       rsh=0
+                       nfs=0e11        js=10u          cj=490u
+                       cjsw=590p       mj=0.46         mjsw=0.46
+                       pb=0.78v        cgdo=320p       cgso=320p
* end penh

vpbulk 1 0 5V
rpbulk 1 0 100meg
vnbulk 2 0 0V
rnbulk 2 0 100meg

* vdd ? 0 5V
* rgnd ? 0 1p
* rvss ? 0 1p

vvdd 6 0 pwl (0.000000e+00 5.000000e+00
+     4.975000e-08 5.000000e+00 5.025000e-08 5.000000e+00)
vsclk_m_0 12 0 pwl (0.000000e+00 0.000000e+00
+     4.975000e-08 0.000000e+00 5.025000e-08 0.000000e+00)
vmosi_m_0 14 0 pwl (0.000000e+00 0.000000e+00
+     4.975000e-08 0.000000e+00 5.025000e-08 0.000000e+00)
vss_m_0 7 0 pwl (0.000000e+00 0.000000e+00
+     4.975000e-08 0.000000e+00 5.025000e-08 0.000000e+00)
vsclk_m_1 13 0 pwl (0.000000e+00 5.000000e+00
+     4.975000e-08 5.000000e+00 5.025000e-08 5.000000e+00)
vmosi_m_1 15 0 pwl (0.000000e+00 5.000000e+00
+     4.975000e-08 5.000000e+00 5.025000e-08 5.000000e+00)
vss_m_1 18 0 pwl (0.000000e+00 5.000000e+00
+     4.975000e-08 5.000000e+00 5.025000e-08 5.000000e+00)
vmiso_s_0 19 0 pwl (0.000000e+00 0.000000e+00
+     4.975000e-08 0.000000e+00 5.025000e-08 0.000000e+00)
vmiso_s_1 20 0 pwl (0.000000e+00 5.000000e+00
+     4.975000e-08 5.000000e+00 5.025000e-08 5.000000e+00)
vs 5 0 pwl (0.000000e+00 2.500000e+00
+     9.750000e-09 2.500000e+00 1.025000e-08 0.000000e+00
+     4.975000e-08 0.000000e+00 5.025000e-08 5.000000e+00)
.print tran v(12) v(14) v(10) v(7) v(13) v(15) v(11) v(18)
.print tran v(3) v(16) v(19) v(8) v(4) v(17) v(20) v(9)
.print tran v(5)
.options cptime = 1000
.tran 1.000000e-10 5.000000e-08
.end
