-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 6-Dec-14 16:57:37
-- Path: /home/jtijhuis/epo3a5/chip/subsystems/SPI/slave/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Spi IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32: STD_LOGIC;
  SIGNAL N_33, N_34, N_35, N_36, N_37, N_38, N_39, N_40: STD_LOGIC;
  SIGNAL N_41, N_42, N_43, N_44, N_45, N_46, N_47, N_48: STD_LOGIC;
  SIGNAL N_49, N_50, N_51, N_52, N_53, N_54, N_55, N_56: STD_LOGIC;
  SIGNAL N_57: STD_LOGIC;
  SIGNAL count_0_port: STD_LOGIC;
  SIGNAL shift: STD_LOGIC;
  SIGNAL count_reset: STD_LOGIC;
  SIGNAL n1: STD_LOGIC;
  SIGNAL count_1_port: STD_LOGIC;
  SIGNAL count_2_port: STD_LOGIC;
  SIGNAL count_3_port: STD_LOGIC;

  SIGNAL read_out_int: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL busy_int: STD_LOGIC;
  SIGNAL sclk_int: STD_LOGIC;
  SIGNAL mosi_int: STD_LOGIC;
  SIGNAL ss_int: STD_LOGIC;

BEGIN

  read_out <= read_out_int;
  busy <= busy_int;
  sclk <= sclk_int;
  mosi <= mosi_int;
  ss <= ss_int;

  read_out_int(7) <= mosi_int;

  ctrl1_U26: no310 PORT MAP (reset, N_50, N_39, N_51);
  ctrl1_U24: no310 PORT MAP (N_52, N_51, N_53, N_55);
  ctrl1_U32: na310 PORT MAP (count_3_port, N_43, N_46, N_49);
  shft1_U57: na310 PORT MAP (N_1, N_2, N_5, N_9);
  shft1_U65: na310 PORT MAP (N_4, N_3, N_6, N_10);
  shft1_U53: na310 PORT MAP (N_7, N_26, N_8, N_18);
  shft1_U61: na310 PORT MAP (N_12, N_11, N_13, N_14);
  shft1_U41: na310 PORT MAP (N_15, N_33, N_16, N_17);
  shft1_U45: na310 PORT MAP (N_28, N_27, N_21, N_25);
  shft1_U49: na310 PORT MAP (N_19, N_20, N_22, N_23);
  shft1_U37: na310 PORT MAP (N_32, N_31, N_34, N_35);
  cnt1_U14: na210 PORT MAP (count_1_port, count_0_port, N_40);
  ctrl1_U37: na210 PORT MAP (N_39, N_38, busy_int);
  ctrl1_U30: na210 PORT MAP (N_49, shift, N_45);
  ctrl1_U29: na210 PORT MAP (N_54, N_45, N_44);
  ctrl1_U35: na210 PORT MAP (send, N_57, N_54);
  shft1_U54: na210 PORT MAP (write_in(4), write_enable, N_8);
  shft1_U60: na210 PORT MAP (read_out_int(5), N_29, N_1);
  shft1_U58: na210 PORT MAP (write_in(5), write_enable, N_5);
  shft1_U59: na210 PORT MAP (read_out_int(4), N_30, N_2);
  shft1_U66: na210 PORT MAP (write_in(7), write_enable, N_6);
  shft1_U67: na210 PORT MAP (read_out_int(6), N_30, N_3);
  shft1_U69: na210 PORT MAP (mosi_int, N_29, N_4);
  shft1_U56: na210 PORT MAP (read_out_int(4), N_29, N_7);
  shft1_U63: na210 PORT MAP (read_out_int(5), N_30, N_11);
  shft1_U62: na210 PORT MAP (write_in(6), write_enable, N_13);
  shft1_U64: na210 PORT MAP (read_out_int(6), N_29, N_12);
  shft1_U44: na210 PORT MAP (read_out_int(1), N_29, N_15);
  shft1_U46: na210 PORT MAP (write_in(2), write_enable, N_21);
  shft1_U50: na210 PORT MAP (write_in(3), write_enable, N_22);
  shft1_U38: na210 PORT MAP (write_in(0), write_enable, N_34);
  shft1_U42: na210 PORT MAP (write_in(1), write_enable, N_16);
  shft1_U48: na210 PORT MAP (read_out_int(2), N_29, N_28);
  shft1_U47: na210 PORT MAP (read_out_int(1), N_30, N_27);
  shft1_U55: na210 PORT MAP (read_out_int(3), N_30, N_26);
  shft1_U51: na210 PORT MAP (read_out_int(2), N_30, N_20);
  shft1_U52: na210 PORT MAP (read_out_int(3), N_29, N_19);
  shft1_U43: na210 PORT MAP (read_out_int(0), N_30, N_33);
  shft1_U40: na210 PORT MAP (read_out_int(0), N_29, N_32);
  shft1_U39: na210 PORT MAP (miso, N_30, N_31);
  cnt1_U12: no210 PORT MAP (N_40, N_42, N_47);
  ctrl1_U31: no210 PORT MAP (N_38, N_39, shift);
  ctrl1_U33: no210 PORT MAP (count_2_port, count_1_port, N_46);
  ctrl1_U22: no210 PORT MAP (clk, count_reset, sclk_int);
  ctrl1_U25: no210 PORT MAP (count_reset, N_49, N_53);
  ctrl1_U27: no210 PORT MAP (send, busy_int, N_52);
  shft1_U68: no210 PORT MAP (N_29, write_enable, N_30);
  shft1_U70: no210 PORT MAP (shift, write_enable, N_29);
  cnt1_U16: ex210 PORT MAP (count_1_port, count_0_port, N_37);
  cnt1_U13: ex210 PORT MAP (N_42, N_40, N_36);
  cnt1_U11: ex210 PORT MAP (count_3_port, N_47, N_48);
  ctrl1_U21: ex210 PORT MAP (N_39, N_38, ss_int);
  cnt1_count_reg_0_inst: dfa11 PORT MAP (N_41, count_reset, sclk_int, count_0_port);
  cnt1_count_reg_2_inst: dfa11 PORT MAP (N_36, count_reset, sclk_int, count_2_port);
  cnt1_count_reg_1_inst: dfa11 PORT MAP (N_37, count_reset, sclk_int, count_1_port);
  cnt1_count_reg_3_inst: dfa11 PORT MAP (N_48, count_reset, sclk_int, count_3_port);
  ctrl1_state_reg_0_inst: dfa11 PORT MAP (N_56, reset, clk, N_39);
  ctrl1_state_reg_1_inst: dfa11 PORT MAP (N_44, reset, clk, N_50);
  shft1_reg_shift_reg_5_inst: dfa11 PORT MAP (N_9, reset, N_24, read_out_int(5));
  shft1_reg_shift_reg_6_inst: dfa11 PORT MAP (N_14, reset, N_24, read_out_int(6));
  shft1_reg_shift_reg_7_inst: dfa11 PORT MAP (N_10, reset, N_24, mosi_int);
  shft1_reg_shift_reg_1_inst: dfa11 PORT MAP (N_17, reset, N_24, read_out_int(1));
  shft1_reg_shift_reg_3_inst: dfa11 PORT MAP (N_23, reset, N_24, read_out_int(3));
  shft1_reg_shift_reg_0_inst: dfa11 PORT MAP (N_35, reset, N_24, read_out_int(0));
  shft1_reg_shift_reg_4_inst: dfa11 PORT MAP (N_18, reset, N_24, read_out_int(4));
  shft1_reg_shift_reg_2_inst: dfa11 PORT MAP (N_25, reset, N_24, read_out_int(2));
  U2: iv110 PORT MAP (clk, n1);
  cnt1_U10: iv110 PORT MAP (count_0_port, N_41);
  cnt1_U15: iv110 PORT MAP (count_2_port, N_42);
  ctrl1_U38: iv110 PORT MAP (N_50, N_38);
  ctrl1_U28: iv110 PORT MAP (shift, count_reset);
  ctrl1_U34: iv110 PORT MAP (count_0_port, N_43);
  ctrl1_U36: iv110 PORT MAP (busy_int, N_57);
  ctrl1_U23: iv110 PORT MAP (N_55, N_56);
  shft1_U71: iv110 PORT MAP (n1, N_24);

END extracted;



