-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 6-Dec-14 16:57:15
-- Path: /home/jtijhuis/epo3a5/chip/subsystems/SPI/slave/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Spi_slave IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32: STD_LOGIC;
  SIGNAL N_33, N_34, N_35, N_36, N_37, N_38, N_39, N_40: STD_LOGIC;
  SIGNAL N_41, N_42: STD_LOGIC;
  SIGNAL n8: STD_LOGIC;
  SIGNAL n10: STD_LOGIC;
  SIGNAL n7: STD_LOGIC;
  SIGNAL n9: STD_LOGIC;
  SIGNAL count_1_port: STD_LOGIC;
  SIGNAL count_2_port: STD_LOGIC;
  SIGNAL count_0_port: STD_LOGIC;
  SIGNAL n3: STD_LOGIC;
  SIGNAL count_reset: STD_LOGIC;
  SIGNAL count_3_port: STD_LOGIC;
  SIGNAL shift_in: STD_LOGIC;

  SIGNAL read_out_int: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL data_ready_int: STD_LOGIC;
  SIGNAL miso_int: STD_LOGIC;

  SIGNAL vss: STD_LOGIC;
  SIGNAL vdd: STD_LOGIC;
BEGIN
  vdd <= '1';
  vss <= '0';

  read_out <= read_out_int;
  data_ready <= data_ready_int;
  miso <= miso_int;

  miso_int <= vdd;

  U16: iv110 PORT MAP (reset, n9);
  U12: iv110 PORT MAP (n8, n7);
  U10: iv110 PORT MAP (sclk, n3);
  shft1_U71: iv110 PORT MAP (sclk, N_31);
  cnt1_U10: iv110 PORT MAP (count_0_port, N_5);
  cnt1_U15: iv110 PORT MAP (count_2_port, N_4);
  U13: na210 PORT MAP (n9, n10, count_reset);
  U14: na210 PORT MAP (count_3_port, n8, n10);
  shft1_U54: na210 PORT MAP (vdd, vss, N_15);
  shft1_U60: na210 PORT MAP (read_out_int(5), N_36, N_8);
  shft1_U58: na210 PORT MAP (vdd, vss, N_12);
  shft1_U59: na210 PORT MAP (read_out_int(4), N_37, N_9);
  shft1_U66: na210 PORT MAP (vdd, vss, N_13);
  shft1_U67: na210 PORT MAP (read_out_int(6), N_37, N_10);
  shft1_U69: na210 PORT MAP (read_out_int(7), N_36, N_11);
  shft1_U56: na210 PORT MAP (read_out_int(4), N_36, N_14);
  shft1_U63: na210 PORT MAP (read_out_int(5), N_37, N_18);
  shft1_U62: na210 PORT MAP (vdd, vss, N_20);
  shft1_U64: na210 PORT MAP (read_out_int(6), N_36, N_19);
  shft1_U44: na210 PORT MAP (read_out_int(1), N_36, N_22);
  shft1_U46: na210 PORT MAP (vdd, vss, N_28);
  shft1_U50: na210 PORT MAP (vdd, vss, N_29);
  shft1_U38: na210 PORT MAP (vdd, vss, N_41);
  shft1_U42: na210 PORT MAP (vdd, vss, N_23);
  shft1_U48: na210 PORT MAP (read_out_int(2), N_36, N_35);
  shft1_U47: na210 PORT MAP (read_out_int(1), N_37, N_34);
  shft1_U55: na210 PORT MAP (read_out_int(3), N_37, N_33);
  shft1_U51: na210 PORT MAP (read_out_int(2), N_37, N_27);
  shft1_U52: na210 PORT MAP (read_out_int(3), N_36, N_26);
  shft1_U43: na210 PORT MAP (read_out_int(0), N_37, N_40);
  shft1_U40: na210 PORT MAP (read_out_int(0), N_36, N_39);
  shft1_U39: na210 PORT MAP (shift_in, N_37, N_38);
  cnt1_U14: na210 PORT MAP (count_1_port, count_0_port, N_3);
  U11: no210 PORT MAP (count_3_port, n7, data_ready_int);
  shft1_U68: no210 PORT MAP (N_36, vss, N_37);
  shft1_U70: no210 PORT MAP (vdd, vss, N_36);
  cnt1_U12: no210 PORT MAP (N_3, N_4, N_7);
  U15: no310 PORT MAP (count_0_port, count_2_port, count_1_port, n8);
  shift_in_reg: dfa11 PORT MAP (mosi, reset, sclk, shift_in);
  shft1_reg_shift_reg_5_inst: dfa11 PORT MAP (N_16, reset, N_31, read_out_int(5));
  shft1_reg_shift_reg_6_inst: dfa11 PORT MAP (N_21, reset, N_31, read_out_int(6));
  shft1_reg_shift_reg_7_inst: dfa11 PORT MAP (N_17, reset, N_31, read_out_int(7));
  shft1_reg_shift_reg_1_inst: dfa11 PORT MAP (N_24, reset, N_31, read_out_int(1));
  shft1_reg_shift_reg_3_inst: dfa11 PORT MAP (N_30, reset, N_31, read_out_int(3));
  shft1_reg_shift_reg_0_inst: dfa11 PORT MAP (N_42, reset, N_31, read_out_int(0));
  shft1_reg_shift_reg_4_inst: dfa11 PORT MAP (N_25, reset, N_31, read_out_int(4));
  shft1_reg_shift_reg_2_inst: dfa11 PORT MAP (N_32, reset, N_31, read_out_int(2));
  cnt1_count_reg_0_inst: dfa11 PORT MAP (N_5, count_reset, n3, count_0_port);
  cnt1_count_reg_2_inst: dfa11 PORT MAP (N_1, count_reset, n3, count_2_port);
  cnt1_count_reg_1_inst: dfa11 PORT MAP (N_2, count_reset, n3, count_1_port);
  cnt1_count_reg_3_inst: dfa11 PORT MAP (N_6, count_reset, n3, count_3_port);
  cnt1_U16: ex210 PORT MAP (count_1_port, count_0_port, N_2);
  cnt1_U13: ex210 PORT MAP (N_4, N_3, N_1);
  cnt1_U11: ex210 PORT MAP (count_3_port, N_7, N_6);
  shft1_U57: na310 PORT MAP (N_8, N_9, N_12, N_16);
  shft1_U65: na310 PORT MAP (N_11, N_10, N_13, N_17);
  shft1_U53: na310 PORT MAP (N_14, N_33, N_15, N_25);
  shft1_U61: na310 PORT MAP (N_19, N_18, N_20, N_21);
  shft1_U41: na310 PORT MAP (N_22, N_40, N_23, N_24);
  shft1_U45: na310 PORT MAP (N_35, N_34, N_28, N_32);
  shft1_U49: na310 PORT MAP (N_26, N_27, N_29, N_30);
  shft1_U37: na310 PORT MAP (N_39, N_38, N_41, N_42);

END extracted;



