-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 17-Nov-14 10:22:25
-- Path: /home/ndewinter/klokdeler/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Klokdeler IS

  SIGNAL N_1: STD_LOGIC;
  SIGNAL d64: STD_LOGIC;
  SIGNAL d2: STD_LOGIC;
  SIGNAL d128: STD_LOGIC;
  SIGNAL d4: STD_LOGIC;
  SIGNAL d256: STD_LOGIC;
  SIGNAL d16384: STD_LOGIC;
  SIGNAL d8192: STD_LOGIC;
  SIGNAL d65536: STD_LOGIC;
  SIGNAL d32768: STD_LOGIC;
  SIGNAL d512: STD_LOGIC;
  SIGNAL d8: STD_LOGIC;
  SIGNAL d4096: STD_LOGIC;
  SIGNAL d1024: STD_LOGIC;
  SIGNAL d32: STD_LOGIC;
  SIGNAL d16: STD_LOGIC;
  SIGNAL d2048: STD_LOGIC;

  SIGNAL f2_int: STD_LOGIC;
  SIGNAL f4_int: STD_LOGIC;
  SIGNAL f8_int: STD_LOGIC;
  SIGNAL f16_int: STD_LOGIC;
  SIGNAL f32_int: STD_LOGIC;
  SIGNAL f64_int: STD_LOGIC;
  SIGNAL f128_int: STD_LOGIC;
  SIGNAL f256_int: STD_LOGIC;
  SIGNAL f512_int: STD_LOGIC;
  SIGNAL f1024_int: STD_LOGIC;
  SIGNAL f2048_int: STD_LOGIC;
  SIGNAL f4096_int: STD_LOGIC;
  SIGNAL f8192_int: STD_LOGIC;
  SIGNAL f16384_int: STD_LOGIC;
  SIGNAL f32768_int: STD_LOGIC;
  SIGNAL f65536_int: STD_LOGIC;
  SIGNAL f131072_int: STD_LOGIC;

BEGIN

  f2 <= f2_int;
  f4 <= f4_int;
  f8 <= f8_int;
  f16 <= f16_int;
  f32 <= f32_int;
  f64 <= f64_int;
  f128 <= f128_int;
  f256 <= f256_int;
  f512 <= f512_int;
  f1024 <= f1024_int;
  f2048 <= f2048_int;
  f4096 <= f4096_int;
  f8192 <= f8192_int;
  f16384 <= f16384_int;
  f32768 <= f32768_int;
  f65536 <= f65536_int;
  f131072 <= f131072_int;


  lbl1_U4: iv110 PORT MAP (d2, f2_int);
  lbl2_U4: iv110 PORT MAP (d4, f4_int);
  lbl6_U4: iv110 PORT MAP (d64, f64_int);
  lbl9_U4: iv110 PORT MAP (d512, f512_int);
  lbl7_U4: iv110 PORT MAP (d128, f128_int);
  lbl8_U4: iv110 PORT MAP (d256, f256_int);
  lbl14_U4: iv110 PORT MAP (d16384, f16384_int);
  lbl15_U4: iv110 PORT MAP (d32768, f32768_int);
  lbl16_U4: iv110 PORT MAP (d65536, f65536_int);
  lbl17_U4: iv110 PORT MAP (N_1, f131072_int);
  lbl13_U4: iv110 PORT MAP (d8192, f8192_int);
  lbl3_U4: iv110 PORT MAP (d8, f8_int);
  lbl4_U4: iv110 PORT MAP (d16, f16_int);
  lbl5_U4: iv110 PORT MAP (d32, f32_int);
  lbl11_U4: iv110 PORT MAP (d2048, f2048_int);
  lbl12_U4: iv110 PORT MAP (d4096, f4096_int);
  lbl10_U4: iv110 PORT MAP (d1024, f1024_int);
  lbl1_state_reg: dfa11 PORT MAP (f2_int, reset, clk, d2);
  lbl2_state_reg: dfa11 PORT MAP (f4_int, reset, d2, d4);
  lbl6_state_reg: dfa11 PORT MAP (f64_int, reset, d32, d64);
  lbl9_state_reg: dfa11 PORT MAP (f512_int, reset, d256, d512);
  lbl7_state_reg: dfa11 PORT MAP (f128_int, reset, d64, d128);
  lbl8_state_reg: dfa11 PORT MAP (f256_int, reset, d128, d256);
  lbl14_state_reg: dfa11 PORT MAP (f16384_int, reset, d8192, d16384);
  lbl15_state_reg: dfa11 PORT MAP (f32768_int, reset, d16384, d32768);
  lbl16_state_reg: dfa11 PORT MAP (f65536_int, reset, d32768, d65536);
  lbl17_state_reg: dfa11 PORT MAP (f131072_int, reset, d65536, N_1);
  lbl13_state_reg: dfa11 PORT MAP (f8192_int, reset, d4096, d8192);
  lbl3_state_reg: dfa11 PORT MAP (f8_int, reset, d4, d8);
  lbl4_state_reg: dfa11 PORT MAP (f16_int, reset, d8, d16);
  lbl5_state_reg: dfa11 PORT MAP (f32_int, reset, d16, d32);
  lbl11_state_reg: dfa11 PORT MAP (f2048_int, reset, d1024, d2048);
  lbl12_state_reg: dfa11 PORT MAP (f4096_int, reset, d2048, d4096);
  lbl10_state_reg: dfa11 PORT MAP (f1024_int, reset, d512, d1024);

END extracted;



