-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 12-Dec-14 20:40:38
-- Path: /home/wbouwmeester/Documents/BetterBlackBox/GWTF/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Blackbox IS


  SIGNAL miso_m_0_int: STD_LOGIC;
  SIGNAL miso_m_1_int: STD_LOGIC;
  SIGNAL sclk_s_0_int: STD_LOGIC;
  SIGNAL mosi_s_0_int: STD_LOGIC;
  SIGNAL ss_s_0_int: STD_LOGIC;
  SIGNAL sclk_s_1_int: STD_LOGIC;
  SIGNAL mosi_s_1_int: STD_LOGIC;
  SIGNAL ss_s_1_int: STD_LOGIC;

BEGIN

  miso_m_0 <= miso_m_0_int;
  miso_m_1 <= miso_m_1_int;
  sclk_s_0 <= sclk_s_0_int;
  mosi_s_0 <= mosi_s_0_int;
  ss_s_0 <= ss_s_0_int;
  sclk_s_1 <= sclk_s_1_int;
  mosi_s_1 <= mosi_s_1_int;
  ss_s_1 <= ss_s_1_int;


  stream2_U9: mu111 PORT MAP (ss_m_0, ss_m_1, s, ss_s_0_int);
  stream0_U9: mu111 PORT MAP (sclk_m_0, sclk_m_1, s, sclk_s_0_int);
  stream1_U9: mu111 PORT MAP (mosi_m_0, mosi_m_1, s, mosi_s_0_int);
  stream3_U9: mu111 PORT MAP (miso_s_0, miso_s_1, s, miso_m_0_int);
  stream2_U8: mu111 PORT MAP (ss_m_1, ss_m_0, s, ss_s_1_int);
  stream0_U8: mu111 PORT MAP (sclk_m_1, sclk_m_0, s, sclk_s_1_int);
  stream1_U8: mu111 PORT MAP (mosi_m_1, mosi_m_0, s, mosi_s_1_int);
  stream3_U8: mu111 PORT MAP (miso_s_1, miso_s_0, s, miso_m_1_int);

END extracted;



